### ISSUE TITLE
Unknown receiver 'ZohoSalesIQ'; did you mean 'RNZohoSalesIQ'?

### ISSUE THREAD

**Issue by mark-slepkov** [zoho/SalesIQ-Mobilisten-ReactNative#1]
Hey there. 
I did all the steps described in the Readme.md and stucked with error: ```Unknown receiver 'ZohoSalesIQ'; did you mean 'RNZohoSalesIQ'?```
in ```..../node_modules/react-native-zohosalesiq-mobilisten/ios/RNZohoSalesIQ.m:18:10: ```

My system information:
MacBook Pro (13-inch, Early 2011)
Mac OS High Sierra 10.13.6
XCode 10.1

It there any chance to run it on my XCode 10.1 cause I haven't ability to upgrade it to 10.3?
Thank you in advance.

**Comment by Angu-G** [comment]
Hi @mark-slepkov , 

Assuming the installation of the framework was successful without errors, can you please confirm us if you get the same issue upon trying to build the project for a non-simulator target? Please try building the project after selecting an actual device or select "Generic iOS Device" as your run target.

**Comment by mark-slepkov** [comment]
Yes. I confirm. Result is still same for both "Generic iOS device" and actual device.

**Comment by shashwatsahu123** [comment]
I'm also getting same issue in ios.

**Comment by Rishabh-Raghunath** [comment]
Could you try searching for the RNZohoSalesIQ.podspec file in the ios folder and replace
`s.vendored_frameworks = "Mobilisten.framework"`
with 
`  s.vendored_frameworks = "Mobilisten.framework",'~> 1.1.0'`
and then run `pod install` and let us know if it fixes the issue? 

Please have "Generic iOS Device" or an actual device selected as well for the run target after following the above steps and try building.
Please let us know if that fixes the issue.

**Comment by Rishabh-Raghunath** [comment]
We have addressed this issue since version `1.1.0` along with a slew of new features and enhancements.
Please update to the above release and run `pod repo update && pod install` from the **iOS** folder in the terminal for your react-native project. After that is done, doing a **clean** and **build** should complete the update and solve the issue.
Please test and let us know to confirm.

**Comment by Rishabh-Raghunath** [comment]
Closing this issue since this has been addressed in newer releases.
