### ISSUE TITLE
Shared desktop not works (only tested on IOS)

### ISSUE THREAD

**Issue by arinconc** [zoho/SalesIQ-Mobilisten-ReactNative#10]
In salesiq there is an option in the chat window that allows a connected user to request a shared desktop.
When I run it, I see in the customer's chat that a message arrives because the list scrolls, but it doesn't show any text.
Do I need to run any ZohoSalesIQ function for it to work?

Thanks!
![shared](https://user-images.githubusercontent.com/1283131/104632599-3a6d5f80-569e-11eb-92a2-31918283a239.png)

**Comment by Rishabh-Raghunath** [comment]
Hi @arinconc
Screensharing using Zoho Assist is not supported currently in the Mobilisten SDK.

**Comment by Rishabh-Raghunath** [comment]
Hi @arinconc 
Screensharing using Zoho Assist is not currently supported via the Mobilisten SDK.
For an immediate resolution, we shall disable the option for chats started from the SDK until the feature is supported.
We will evaluate and might support this in a future update. We are closing this issue for now.
