### ISSUE TITLE
[Android] Calling setLanguage updates texts on Emulator but not on Real Device 

### ISSUE THREAD

**Issue by gitChaoslord** [zoho/SalesIQ-Mobilisten-ReactNative#109]
Hello,
I've encountered a translation related problem that appears only on a physical Android device and would like some help.

### Description
I am calling the setLanguage method of ZohoSalesIQ like this, in one of my Screens
```
import { ZohoSalesIQ } from 'react-native-zohosalesiq-mobilisten'

. . .

 const { i18n } = useTranslation()

  useEffect(() => {
      ZohoSalesIQ.setLanguage(i18n.language)
  }, [i18n.language])
```

Afterwards, I invoke IsChatEnabled and openChat methods to launch SalesIQ chat.

In IOS everything works flawlessly, changing the language and re-opening the chat shows the texts translated to the new language.
In Android, everything works fine on the Emulator but once I launch it on a physical device, only the english texts are displayed regardless of language selected.

Note: I use the provided default strings and no custom strings as described [here](https://www.zoho.com/salesiq/help/developer-guides/android-mobile-sdk-theme-customization-strings-2.0.html)

Any help is welcome,
Thanks in advance!

### Environment
  React-native: 0.74.5
  react-native-zohosalesiq-mobilisten: 10.0.3
  Expo: no
  Node: 18
  Emulator Android Version: 13 (API 33), 14 (API 34), 15 (API 35)
  Physical Android Version: 13
  Locale codes: ar (arabic), de (german), fr (french), en (english - default), el (greek), it (italian), zh (chinese)

**Comment by bhahirathan-mb-11956** [comment]
Hi @gitChaoslord ,
 
We apologize for the inconvenience. We checked the setLanguage() API in Android with a physical device, and it's working fine on our side.
 
We need to debug this case further on your side, so please send us your portal, brand, screen recording(if possible), and the code snippets you're using for Mobilisten to [support@zohosalesiq.com](mailto:support@zohosalesiq.com).
 
We will be happy to assist you.
 
Regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by gitChaoslord** [comment]
Hello again,

I followed the instructions received in the support email to the letter and everything is working smoothly right now.

Apparently, the root cause of my issue was the fact that I was calling `registerVisitor(user_unique_id)` immediately after `setLanguage()`,  resulting in language being cleared sometimes.

Thanks @bhahirathan-mb-11956 

In case anyone else encounters a similar issue, here is a summary of the instructions I received.

 - ZohoSalesIQ.registerVisitor(user_unique_id) API should be called only after the user's login is successful, including the setVisitorName() and setVisitorEmail() functions, within the success callback of the user's login in the app. Similarly, use ZohoSalesIQ.unregisterVisitor() during the user's logout. - Note: registerVisitor() is asynchronous
 - The setLanguage() function should be used in the following scenarios
    + Inside the ZohoSalesIQ.initWithCallback() success.
    + Inside the ZohoSalesIQ.registerVisitor() success.
    + Whenever the user changes the language.

Feel free to close this issue
