### ISSUE TITLE
Build failure in Xcode 12.4

### ISSUE THREAD

**Issue by musthu786** [zoho/SalesIQ-Mobilisten-ReactNative#13]
build crashing with issues 

![IMG_20210329_120849](https://user-images.githubusercontent.com/79713827/112796704-32775780-901f-11eb-9fd2-1595609c1abd.jpg)

**Comment by Rishabh-Raghunath** [comment]
@musthu786 Thanks for reaching out.
The issue you have reported is not a crash but a build failure and is caused to an issue in the Xcode build settings for the project.
Please refer to [Issue #11](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/issues/11) for the solution to the issue.

**Comment by musthu786** [comment]
"Do you happen to have VALID_ARCHS defined under the User-Defined section under Build Settings on Xcode 12?
If you do, please try removing the same from the main and Pods projects and try a project clean and build."
didn't find this under User-Defined section
