### ISSUE TITLE
[react-native][Android] App crashes on launch due to 'Attempt to invoke virtual method...'

### ISSUE THREAD

**Issue by Md-Mudassir** [zoho/SalesIQ-Mobilisten-ReactNative#15]
in iOS its working fine but in android its throwing the below error on app launch.

**Reason**
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.zoho.commons.LauncherProperties.getIcon()' on a null object reference`

**Stacktrace**
```
FATAL EXCEPTION: main
Process: com.careerlabs, PID: 23555
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.zoho.commons.LauncherProperties.getIcon()' on a null object reference
at com.zoho.livechat.android.operation.SalesIQApplicationManager$7$1.run(SalesIQApplicationManager.java:984)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

"react-native": "^0.64.0",

**Comment by Angu-G** [comment]
@Md-Mudassir, Can you please let us know is this always reproducible and also whether you have used the following [API](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-operator-image-chat.html)?

**Comment by Md-Mudassir** [comment]
@Angu-G I followed [this](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-installation.html) setup docs. & i'm calling only these 2 API's in one of my component.

`ZohoSalesIQ.init("android_app_key","android_access_key");
ZohoSalesIQ.setLauncherVisibility(true);`

iOS works no issues, only in android it throws the error. below error was captured in firebase crashlytics.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.graphics.drawable.Drawable com.zoho.commons.LauncherProperties.getIcon()' on a null object reference
com.zoho.livechat.android.operation.SalesIQApplicationManager$7$1.run (SalesIQApplicationManager.java:984)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7656)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)

```
Is there are any additionaly setup which i'm missing for android?

**Comment by Angu-G** [comment]
@Md-Mudassir, Can you please try the following code block as a replacement of the ZohoSalesIQ.init() API and let us know that the issue persists?

```
ZohoSalesIQ.initWithCallback("your appKey","your accessKey", (success) => {
      if(success){
          ZohoSalesIQ.setLauncherVisibility(true);
      }
      else{
          // your code
      }
});
```

**Comment by Md-Mudassir** [comment]
@Angu-G tried it but callback is returning false.. success seems to be false

**Comment by Angu-G** [comment]
@Md-Mudassir Please share your screen name(portal name)

**Comment by Md-Mudassir** [comment]
portal name? sorry i don't understand..

**Comment by Angu-G** [comment]
![image](https://user-images.githubusercontent.com/58692424/114678899-50d09900-9d29-11eb-8c9d-d9a8b7505a29.png)
You can take this from your salesiq dashboard and share to us

**Comment by Angu-G** [comment]
Yes, @Md-Mudassir. Let me check and get back

**Comment by Md-Mudassir** [comment]
> @Md-Mudassir, Can you please try the following code block as a replacement of the ZohoSalesIQ.init() API and let us know that the issue persists?
> 
> ```
> ZohoSalesIQ.initWithCallback("your appKey","your accessKey", (success) => {
>       if(success){
>           ZohoSalesIQ.setLauncherVisibility(true);
>       }
>       else{
>           // your code
>       }
> });
> ```

Even in iOS its returning false.. where as `ZohoSalesIQ.init()` works (iOS)

**Comment by Md-Mudassir** [comment]
@Angu-G any fix for the above issue? and apart from that i have 2 questions..
1. The floating icon is by default set globally in almost all of the components.. ideally it should only appear in one component where I am defining `ZohoSalesIQ.setLauncherVisibility(true);` right? is there a way to control it to appear only in specified component?
2. How to customize the floating icon like color, position..

**Comment by Angu-G** [comment]
@Md-Mudassir Thank you for your patience. We have identified the issue. Our server team is checking for the mismatch in the key. We will revert back once the fix is live.

**Comment by Angu-G** [comment]
> @Angu-G any fix for the above issue? and apart from that i have 2 questions..
> 
> 1. The floating icon is by default set globally in almost all of the components.. ideally it should only appear in one component where I am defining `ZohoSalesIQ.setLauncherVisibility(true);` right? is there a way to control it to appear only in specified component?
> 2. How to customize the floating icon like color, position..

@Md-Mudassir Customization is not possible as of now. You could have your own custom launcher and call the [openChat()](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-open-chat.html) to open the SDK.

**Comment by Md-Mudassir** [comment]
@Angu-G one more bug `ZohoSalesIQ.openChat()` doesn't open the chat in Android.

**Comment by Md-Mudassir** [comment]
> > @Md-Mudassir, Can you please try the following code block as a replacement of the ZohoSalesIQ.init() API and let us know that the issue persists?
> > ```
> > ZohoSalesIQ.initWithCallback("your appKey","your accessKey", (success) => {
> >       if(success){
> >           ZohoSalesIQ.setLauncherVisibility(true);
> >       }
> >       else{
> >           // your code
> >       }
> > });
> > ```
> 
Thanks for the fix @Angu-G 
using the above API inside `useEffect` fixed the problem & for customisation I turned ` ZohoSalesIQ.setLauncherVisibility(false);` to false & made use of `openChat()` API and added my own floating icon in which i had the full control over it.

**Comment by Angu-G** [comment]
@Md-Mudassir, Thank you for your time over the screen-sharing session. SDK should always be initialized at the Application level. In React-Native case, we recommend initializing the SDK in `useEffect` or `componentDidMount` method.
