### ISSUE TITLE
Invalid Resource error when initializing the SDK. 

### ISSUE THREAD

**Issue by alihassan0** [zoho/SalesIQ-Mobilisten-ReactNative#16]
Hello There,

 I have been using the SDK for a few months now. and it was working great. but suddenly I find that the sdk no longer opens. debugging further it seems initializing the sdk no longer works even though I double check the app key & access key. and I have a deployed version where the sdk works. After going through the logs I found this error. so I assume it's from the [backend ](https://www.zoho.com/salesiq/help/developer-section/rest-api-v2.html) but I can't figure out exactly what to change since I am just initializing the app nothing more. 
``` 
❌ MOBILISTEN » INIT FAILED: CODE: 1019 MESSAGE: Invalid Resource
```

Thanks

**Comment by Rishabh-Raghunath** [comment]
Hi @alihassan0,
Thanks for reaching out. Could you help us with your portal name so we can check this further?

**Comment by alihassan0** [comment]
Thanks for the quick reply. 

not sure what the portal name is but the company Name is "Ackoo"

https://salesiq.zoho.com/ackoo

**Comment by Rishabh-Raghunath** [comment]
Great. It looks like you might be appending ".dev" to the bundle ID that is registered on the SalesIQ console.
Could you recheck your bundle ID and let me know if all works fine?

**Comment by alihassan0** [comment]
Just tested it and it works. Thanks a lot !!
we have a dev & production as two different schemas. the dev one's bundle id is postfixed with .dev
So I guess now it only works on the production one. 

Thanks a lot for the quick turnaround <3 . and if I may suggest a better error message as I have spent around 4 hours trying everything to figure out why it won't work.

**Comment by Rishabh-Raghunath** [comment]
Great to hear that it's working now. 
And sure we'll take that as feedback. Thanks.
