### ISSUE TITLE
The package name is very generic com.reactlibrary

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#17]
Please change to your package like "com.zohosalesiq.mobilisten", the library com.reactlibrary was conflict on my application. I cannot make it works due to the "com.reactlibrary" is already declared by another module on "node_modules"

**Comment by Angu-G** [comment]
@dieptang Thanks for reporting. We are already working on it. You can expect the update on or before Friday.

**Comment by dieptang** [comment]
@Angu-G  Thanks for your reply, it will be great.

**Comment by Angu-G** [comment]
@dieptang, We have rolled out the fix for this issue in [v4.0.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.0.0). Please reinstall the package and let us know here if any other support is required.

**Comment by dieptang** [comment]
@Angu-G Yeah, it's working perfect now on Android. Thank you.

**Comment by Angu-G** [comment]
Thanks, @dieptang. Closing the issue.
