### ISSUE TITLE
Feature request: Display conversation on the page/screen

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#18]
Hello again,

Thanks for the previous great support, I want to customize more flexible on our application, I will make the single page as a support live chat and it should be display the conversation/dashboard instead of showing the Launcher everywhere. Like the image below

![image](https://user-images.githubusercontent.com/7411097/126735322-817a09be-ccf8-46b6-91b3-377cca277f12.png)
 
Is there any function for that, ZohoSalesIQ.openChat(); and ZohoSalesIQ.setLauncherVisibility(); not helpful, 

Thank you.

**Comment by Angu-G** [comment]
Hello @dieptang, We do have an internal API to fetch the list of conversations [.getChats()](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-get-chats.html). It will return the conversations with the properties mentioned [here](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-chat-v2.html). You can populate the list in your own UI and upon tapping of particular conversation you can trigger [.openChatWithID()](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-open-chat-with-id.html) API to open the chat window.

**Comment by dieptang** [comment]
@Angu-G  Okay ;) only wondering if the API have the function already with one line of code will more easy. Anyhow I will improve on my application later. Thank you.

**Comment by hieplam** [comment]
@dieptang Hi i'm having trouble in localize in VN, can we have a chat by email?

**Comment by Angu-G** [comment]
Hi @hieplam, please write to us at support[at]zohosalesiq[dot]com.
