### ISSUE TITLE
custom localization in chat module

### ISSUE THREAD

**Issue by hieplam** [zoho/SalesIQ-Mobilisten-ReactNative#19]
Hi can we support custom localization (vietnamese) or just custom text in any language. right now my app really really need to  have localize cause it only serve for our people. So it would be nice if there is anyway to custom texts especially in chat module

**Comment by dieptang** [comment]
> Hi can we support custom localization (vietnamese) or just custom text in any language. right now my app really really need to have localize cause it only serve for our people. So it would be nice if there is anyway to custom texts especially in chat module

@hieplam You may give it a try here https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-strings.html

**Comment by Angu-G** [comment]
Hello @hieplam, We hope you have tried the customization with the help of the following [link](https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-strings.html).
Closing this issue here. You can write back if further support is needed.
