### ISSUE TITLE
Use of deprecated UIWebView in iOS

### ISSUE THREAD

**Issue by diegogurpegui** [zoho/SalesIQ-Mobilisten-ReactNative#2]
When uploading a project to Apple with this component, this warning is returned:
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.

The use of UIWebView is deprecated and this project seems to be using it based on this search:
`grep -r UIWebView node_modules/*`

The problem is that it seems to be used in binary files, which there is no way of easily change. Is there any plan to update this? Otherwise every project using this will eventually face big problems.

**Comment by mark-slepkov** [comment]
Same problem for me. Is there any solution?

**Comment by diegogurpegui** [comment]
I tried replacing the binaries in this component with the ones in:
https://github.com/zoho/SalesIQ-Mobilisten-iOS/
But it didn't work, which leads me to think that the iOS native SDK is not compatible either (or that I replaced them wrong).

**Comment by Rishabh-Raghunath** [comment]
The native iOS SDK has been updated to use WKWebView instead of UIWebView.
As an immediate workaround, you can replace the binary **Mobilisten.framework** and that should solve the issue.
You can find the latest builds of the framework from: 
https://github.com/zoho/SalesIQ-Mobilisten-iOS/
We will be releasing an update shortly for react native as well to have this resolved.

**Comment by diegogurpegui** [comment]
Thanks for the response Rishabh!
We did that workaround last week and made it work for the time being. We
look forward to the update on the SDK.

Best

**Comment by Angu-G** [comment]
We have rolled out an update with the WKWebView. 
[react-native-zohosalesiq-mobilisten](https://www.npmjs.com/package/react-native-zohosalesiq-mobilisten)

**Comment by Rishabh-Raghunath** [comment]
Closing this issue.
Update with the WKWebView change has been moved live with version 0.1.0.
