### ISSUE TITLE
Bug: setThemeColorforiOS not working properly [fixed]

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#20]
@Angu-G  I want to report few bugs directly here:

`ZohoSalesIQ.setChatTitle("Support title");
ZohoSalesIQ.startChat("The invoice incorrectly");

 // either ZohoSalesIQ.openChat();
 ZohoSalesIQ.setConversationVisibility(true);`

1. On react native, after I call the code above for set the title and the content, then after I end the chat, and I click Launcher button for make new conversation, it's always take old content "The invoice incorrectly" and the old title. How I can empty these content on new chat?

![image](https://user-images.githubusercontent.com/7411097/126856498-3ea6fc35-f43a-4b29-a2a6-53eecabb4484.png)

2. I'm not found the customize background color for send button from the chat. I checked all page here but did not found https://www.zoho.com/salesiq/help/developer-section/android-mobile-sdk-theme-customization-chat-input.html

![image](https://user-images.githubusercontent.com/7411097/126856429-8b34c67a-dc41-401d-ac98-23259e6a8b23.png)

3. Suggestion: For the React Native, it should be able to customize string and color directly, currently I must come to android/strings.xml and ios pod path for customize everything. Also for Android if should be have the function for set themeColor like from IOS, that we set the primary color only and everything on Chat should be change accordingly.

**Comment by Angu-G** [comment]
Hello @dieptang, 
> 1. On react native, after I call the code above for set the title and the content, then after I end the chat, and I click Launcher button for make new conversation, it's always take old content "The invoice incorrectly" and the old title. How I can empty these content on new chat?
    
 It is intended to work in this way. If you want to clear the old message, you can try it out by passing an empty string in the API or if you want to replace the old content with a new one, pass the new message(title) before initiating the chat.


> 2. I'm not found the customize background color for send button from the chat. I checked all page here but did not found
   
 Attribute name **`colorAccent`** can be used to change the color of the send button. We will document the same.


> 3. Suggestion: For the React Native, it should be able to customize string and color directly, currently I must come to android/strings.xml and ios pod path for customize everything. Also for Android if should be have the function for set themeColor like from IOS, that we set the primary color only and everything on Chat should be change accordingly.

 And regarding this suggestion, We will check for the feasibility and let you know.
 
 If you need real-time assistant in customization or have further queries/suggestions, please drop a mail to us at support[at]zohosalesiq[dot]com so that we can help you through a session and get it cleared in a single stretch.

**Comment by dieptang** [comment]
@Angu-G thanks for your reply.

Converning to (2). It should be something like 

`<item name="siq_chat_message_backgroundcolor_visitor">@color/primary</item>` 

Can you document it here more clearly? 

I have new issue, How can I customize the color and text strings for IOS? I found the guide below but I don't know where to put these code. And the customize for the text language also not documented yet for IOS.

![image](https://user-images.githubusercontent.com/7411097/126863054-47061f4d-e705-4175-b053-9cfa090a1ec8.png)

**Comment by Angu-G** [comment]
> Converning to (2). It should be something like
> 
> `<item name="siq_chat_message_backgroundcolor_visitor">@color/primary</item>`
> 
> Can you document it here more clearly?

The attribute you specified will be used to change the visitor sent messages bubble background color.

Example code for colorAccent attribute:
`<item name="colorAccent"><your color code></item>`



> I have new issue, How can I customize the color and text strings for IOS? I found the guide below but I don't know where to put these code. And the customize for the text language also not documented yet for IOS.

Regarding your query for iOS, you may use the [ZohoSalesIQ.setThemeColorforiOS()](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-chat-theme-ios.html) API to set the overall theme color.
However, if you wish to customize the theme more extensively as shown in the native SDK documentation in react native, it would involve including the code to set a custom theme within the plugin's source by creating a fork.

You may use the same [.setChatTitle()](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-chat-title.html) API for iOS as well for setting the title. Extensive string customization has not been supported yet in iOS although this is in our roadmap.

**Comment by dieptang** [comment]
@Angu-G Yes, The colorAccent work fine now.

Concerning to the themecolor on IOS, I call function ZohoSalesIQ.setThemeColorforiOS("#E7272D"); , but it;s not working. Still showing default blue color, can you please check one again?

**Comment by dieptang** [comment]
Update: The function SetThemeColorforIOS only working sometime. It's not stable working. For example, it's changed the color from the menu End chat only. All other section still blue. 

![image](https://user-images.githubusercontent.com/7411097/126893894-14535b30-5831-421a-9f57-1de5d2635d57.png)

I suppose it's a bug.

Another problem, that from the IOS, We cannot work with the UIModel

=====
 <UIModal ref={modalRef} disabled>
        <PopupQuestionHor
          actionReject={() => {
            modalRef.current.setModalVisible(false);
          }}
          actionSubmit={() => {
            modalRef.current.setModalVisible(false);
            ZohoSalesIQ.setConversationVisibility(true);
          }}
          title={'Question?'}
          content={'Do you want connect to support chat?'}
          txtReject={'No'}
          txtSubmit={'Yes'}
        />
      </UIModal>

============

It's showing up, then closing immediately, please try reproduce from your side.

**Comment by Rishabh-Raghunath** [comment]
Hello @dieptang, could you confirm that the `setThemeColorforiOS` API is invoked immediately after calling the init API?

Regarding your second query with the shared code snippet, 
```javascript
actionSubmit= {() => {
    modalRef.current.setModalVisible(false);
    ZohoSalesIQ.setConversationVisibility(true);
}};
```
We see that the [`ZohoSalesIQ.setConversationVisibility`](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-conversation-visibility.html) API is invoked after calling dismiss on a modal. The above API is used to toggle the conversations history page within the SDK UI and does not function to open the SDK if this is the intended flow.

**Comment by dieptang** [comment]
@Rishabh-Raghunath Yes, I confirm there are an issue here, the `setThemeColorforiOS ` is called after the Init function.

`ZohoSalesIQ.init("ios_app_key","ios_access_key");
ZohoSalesIQ.setThemeColorforiOS("#E7272D");
ZohoSalesIQ.setLauncherVisibility(true);`

**Comment by Rishabh-Raghunath** [comment]
Interesting. Could you try using the below code snippet instead?
```javascript
ZohoSalesIQ.initWithCallback("ios_app_key" ,"ios_access_key", (_) => {
  ZohoSalesIQ.setThemeColorforiOS("#E7272D");
  ZohoSalesIQ.setLauncherVisibility(true);
});
```
We have fixed a minor issue relating to the behavior described by you in an upcoming update. But we hope the above snippet of code works for you.

**Comment by dieptang** [comment]
@Rishabh-Raghunath confirmed it's not work properly also with initWithCallback, sometime it's colored, sometime it's showing default color. 
For example, I open the launcher, it's showing default color - blue, click on new chat - showing my color (red), then sometime switch back default color.

![image](https://user-images.githubusercontent.com/7411097/126899575-215f8a75-c0fd-4855-a68b-943087dda867.png)
![image](https://user-images.githubusercontent.com/7411097/126899576-42263b18-3e9e-4077-afe8-3f9ff25e98a6.png)

It should be change the main color on everything from blue to my color.

Also another thing, How Can we deactivate night mode? because my application doesn't support night mode. 
Thank you.

**Comment by Rishabh-Raghunath** [comment]
We shall investigate this further and keep you posted.
To disable dark mode support in the application, set the value of the [**`UIUserInterfaceStyle`**](https://developer.apple.com/documentation/bundleresources/information_property_list/uiuserinterfacestyle) property to **`Light`** in the application's **Info.plist** file.

**Comment by hieplam** [comment]
i'm having same issue on `setThemeColorforiOS`, in my case none of above solution worked. Is there any way to work around while wait for the next release fix?

**Comment by hieplam** [comment]
@dieptang for customize text strings in ios, i found a work around for this. 

go to `Pods//Mobilisten/Mobilisten.xcframework/[[BUILDPLATFORM]]/Mobilisten.framework` there are lots of localization files named `LCLocalizable_[Region code].strings`

pick any file you want to customize, change extension to .plist, open and edit the text to language you want. 

You can do that. as a temporary work around to localize sales iq chat on iOS

**Comment by Rishabh-Raghunath** [comment]
Hello @dieptang and @hieplam,
We have now released an update, version [4.0.1](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.0.1) where the issue with setting the theme color should be addressed.

We request you to try updating to the latest version and ensure that the `setThemeColorforiOS` API is invoked right after using the init API.

**Comment by hieplam** [comment]
`setThemeColorforiOS` worked as expected , thanks

**Comment by dieptang** [comment]
@Rishabh-Raghunath Thank for updating, I will try and update back to you.

**Comment by dieptang** [comment]
@Rishabh-Raghunath Thanks for resolve the issue, working mostly fine now. I found 2 small issue

1. When connected to the operator.
![image](https://user-images.githubusercontent.com/7411097/127630548-9e0f4755-2077-4f72-b4dc-abf019be8670.png)

2. Open status still green

![image](https://user-images.githubusercontent.com/7411097/127630600-3a88d647-836f-4e0e-8ace-2200cec60326.png)

**Comment by dieptang** [comment]
> @dieptang for customize text strings in ios, i found a work around for this.
> 
> go to `Pods//Mobilisten/Mobilisten.xcframework/[[BUILDPLATFORM]]/Mobilisten.framework` there are lots of localization files named `LCLocalizable_[Region code].strings`
> 
> pick any file you want to customize, change extension to .plist, open and edit the text to language you want.
> 
> You can do that. as a temporary work around to localize sales iq chat on iOS

The new LCLocalizable_[Region code].strings file should be put on the same folder   `Pods//Mobilisten/Mobilisten.xcframework/[[BUILDPLATFORM]]/Mobilisten.framework` right ?

**Comment by hieplam** [comment]
The new LCLocalizable_[Region code].strings file should be put on the same folder Pods//Mobilisten/Mobilisten.xcframework/[[BUILDPLATFORM]]/Mobilisten.framework right ?
==> Yes, just overwrite it.

for open and change it. Try to close all xcode process -> change file from `.strings` to `.plist` and open it.
In my machine, it open using xCode

**Comment by dieptang** [comment]
> The new LCLocalizable_[Region code].strings file should be put on the same folder Pods//Mobilisten/Mobilisten.xcframework/[[BUILDPLATFORM]]/Mobilisten.framework right ?
> ==> Yes, just overwrite it.
> 
> for open and change it. Try to close all xcode process -> change file from `.strings` to `.plist` and open it.
> In my machine, it open using xCode
> 
> Also , change its back to `.strings` after you edit text, and run ios, the text should be effect now :))

Strange. I overwritten  LCLocalizable_EN.strings and/or add LCLocalizable_VI.strings also not working. Any hint?

![image](https://user-images.githubusercontent.com/7411097/127736693-a39f1397-0e31-4a73-bcec-c8bab6018a51.png)

**Comment by Rishabh-Raghunath** [comment]
Hi @dieptang, the color applied in the open chat badge and the connected information background is green by design and the theme color is not applied in the mentioned places using the [`setThemeColorforiOS`](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-chat-theme-ios.html) API.

However, if you are able to import Mobilisten in the AppDelegate in native code as shown below:
```objc
#import <Mobilisten/Mobilisten.h>
``` 
Changing the chat open badge color is possible using the native `Theme` APIs. You may refer to the [`Conversation.ListItem.openBadgeBackgroundColor`](https://www.zoho.com/salesiq/help/developer-section/ios-mobile-sdk-theme-customization-conversation.html) attribute. You may add this to the **application(_:didFinishLaunchingWithOptions:)** method.

**Example**:
```objc
  UIColor *themeColor = UIColor.redColor;
  SIQTheme *theme = [[ZohoSalesIQ Theme] baseTheme];
  [theme setThemeColor:themeColor];
  [[[theme Conversation] ListItem] setOpenBadgeBackgroundColor:themeColor];
  [[ZohoSalesIQ Theme] setThemeWithTheme:theme];
```

> **Note**: You would need to remove the usage of **setThemeColorforiOS** API if you are setting a new theme this way. The above code also sets the theme color.

Changing the color of the connected information background is not possible at the given moment. We shall keep you posted once this is added to the framework in a future update.

**Comment by arthedza** [comment]
> Hi @dieptang, the color applied in the open chat badge and the connected information background is green by design and the theme color is not applied in the mentioned places using the [`setThemeColorforiOS`](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-chat-theme-ios.html) API.
> 
> However, if you are able to import Mobilisten in the AppDelegate in native code as shown below:
> 
> ```objc
> #import <Mobilisten/Mobilisten.h>
> ```
> 
> Changing the chat open badge color is possible using the native `Theme` APIs. You may refer to the [`Conversation.ListItem.openBadgeBackgroundColor`](https://www.zoho.com/salesiq/help/developer-section/ios-mobile-sdk-theme-customization-conversation.html) attribute. You may add this to the **application(_:didFinishLaunchingWithOptions:)** method.
> 
> **Example**:
> 
> ```objc
>   UIColor *themeColor = UIColor.redColor;
>   SIQTheme *theme = [[ZohoSalesIQ Theme] baseTheme];
>   [theme setThemeColor:themeColor];
>   [[[theme Conversation] ListItem] setOpenBadgeBackgroundColor:themeColor];
>   [[ZohoSalesIQ Theme] setThemeWithTheme:theme];
> ```
> 
> > Note: You would need to remove the usage of **setThemeColorforiOS** API if you are setting a new theme this way. The above code also sets the theme color.
> 
> Changing the color of the connected information background is not possible at the given moment. We shall keep you posted once this is added to the framework in a future update.

Tried this but got an error
![Screenshot 2022-08-25 at 13 48 09](https://user-images.githubusercontent.com/9218476/186646995-34b4deb5-109f-4381-b1ef-d9e56270bd28.png)
![Screenshot 2022-08-25 at 13 55 53](https://user-images.githubusercontent.com/9218476/186647005-e09ec489-9d75-4f40-a618-3152d8b94e0d.png)
![Screenshot 2022-08-25 at 13 56 58](https://user-images.githubusercontent.com/9218476/186647007-2dc83fc4-5b2f-47d5-bb7a-365bb8761b30.png)

**Comment by arthedza** [comment]
https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/issues/47
