### ISSUE TITLE
Got null pointer exception 

### ISSUE THREAD

**Issue by hungkoala** [zoho/SalesIQ-Mobilisten-ReactNative#24]
![Error](https://i.ibb.co/1J7rP0C/z2651758917038-d1a34135d03c35ab055127cc7b3c35a9.jpg)

**Comment by Angu-G** [comment]
@hungkoala Can you please help us with the complete error log to debug further from our end?

**Comment by hungkoala** [comment]
the bug is fixed by using ZohoSalesIQ.initWithCallback() instead of ZohoSalesIQ.init(), bad document

**Comment by Angu-G** [comment]
Hi @hungkoala, Our team is already working on the adaption of initWithCallback() API on the installation page. We shall update here once the changes are live. Thank you for your feedback!

**Comment by Angu-G** [comment]
Hello @hungkoala, We have updated the documentation with the initWithCallback() API(in the [Installation](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-installation.html) page). 
Thank you!!

**Comment by hungkoala** [comment]
great
