### ISSUE TITLE
ZohoSalesIQ.initWithCallback not working in Android 

### ISSUE THREAD

**Issue by rasheedbengaluru** [zoho/SalesIQ-Mobilisten-ReactNative#27]
var appKey;
var accessKey;

if (Platform.OS === 'ios') {
    appKey = "xxxxxxxxx";
    accessKey = "xxxxxxxxxx";
} else {
    appKey = "xxxxxxxxx";
    accessKey = "xxxxxxxxxx";
}

ZohoSalesIQ.initWithCallback(appKey, accessKey, (success) => {
  if (success) {
 
  
  } else {
      // your code to handle initialization failure
      Alert.alert('Error','Zoho init failed')
  }
});

I am able to see my zoho chat floating icon in IOS and all are working fine for my iOS.
But Android i am getting in to else part.

Chat doesnt seems to be initializing.

 Alert.alert('Error','Zoho init failed')

**Comment by Angu-G** [comment]
Hi @rasheedbengaluru, Can you please share with us your portal/screen name to debug the credentials on our side.

**Comment by rasheedbengaluru** [comment]
Study-MRCOG-Mobile-Dev

**Comment by Angu-G** [comment]
Hi, seems the department "Mobile App Development" is either private or disabled in the portal. Can you enable it or make it public if it is private and reinstall the application?

**Comment by rasheedbengaluru** [comment]
ya its private now
let me make it public and check

**Comment by rasheedbengaluru** [comment]
Thanks, its working now, after making department public

**Comment by Angu-G** [comment]
Thank you @rasheedbengaluru, Closing the issue.
