### ISSUE TITLE
Error com.zoho.livechat.android.config.DeviceConfig.getPreferences 

### ISSUE THREAD

**Issue by feleko** [zoho/SalesIQ-Mobilisten-ReactNative#28]
Hey,
I got fatal error: Fatal Exception: java.lang.NullPointerException.
Unable to start application.
Wykorzystuje wersje  4.1.0
![Screenshot 2021-09-22 at 11 17 03](https://user-images.githubusercontent.com/22773283/134317094-d820deb0-9eec-46dc-83c6-fdd8506ed37d.png)

**Comment by Angu-G** [comment]
Hello @feleko, This issue happens when registerVisitor() API is triggered before init() API gets completed. Can you please confirm for me on that? The following syntax would be handy. Please have a try on this too.

ZohoSalesIQ.initWithCallback(appKey, accessKey, (success) => {
    if (success) {
        ZohoSalesIQ.registerVisitor("registerID");
    } else {
        
    }
});

**Comment by feleko** [comment]
Thanks for your help.
