### ISSUE TITLE
Got the error at runtime on customer device "Only one Looper may be created per thread"

### ISSUE THREAD

**Issue by hungkoala** [zoho/SalesIQ-Mobilisten-ReactNative#33]
RuntimeException: Only one Looper may be created per thread
    at android.os.Looper.prepare(Looper.java:101)
    at android.os.Looper.prepare(Looper.java:96)
    at com.zoho.livechat.android.utils.LDPEXUtil.run(LDPEXUtil.java:49)

Android Version:7.0 

G3312 Model:43.0.A.7.106

**Comment by Angu-G** [comment]
Hello @hungkoala, This might happen when we connect to the internet from our end and at the same time Android system (core Android code) might use some UI level operations with the main thread. This shouldn't cause any trouble at the UI level of your application.
Anyways we can handle this exception too in our upcoming release. Thanks for bringing this to our notice. We shall update you in our previous thread #Issue30 about the fix roll-out.

**Comment by Angu-G** [comment]
Hello @hungkoala, Thank you for your patience. This issue has been addressed in our latest [version(v4.2.4](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.4)).
