### ISSUE TITLE
We got ‘we missed your chat request’

### ISSUE THREAD

**Issue by feleko** [zoho/SalesIQ-Mobilisten-ReactNative#34]
We can able to put one message and then we got 'we missed your chat request' and there is no text input anymore.
The problem occurs on iOS.
We call after initWithCallback() call.

![image](https://user-images.githubusercontent.com/22773283/143431538-2755f336-08d5-4208-bde5-f9a8676fd260.png)

**Comment by Angu-G** [comment]
Hi @feleko, Can you please share with us your screen name from the salesiq portal to debug further?

**Comment by Angu-G** [comment]
Hi @feleko,we are closing this issue since this has no recent activities. You can reach back us if you need further support. 
Please note that chats will get missed outside business hours if configured in the same way.
