### ISSUE TITLE
NullPointerException - getMsgid() on a null object reference

### ISSUE THREAD

**Issue by MelanieJourne** [zoho/SalesIQ-Mobilisten-ReactNative#38]
Hello,

I have the sdk install in my app and so far no problem.
However, I have a bug that starts reporting from my bug tracking platform (Sentry). 
It happens when the chatbot asked my user for this address mail and he types it and sends it.
You can see the details below: 
![Capture d’écran 2022-02-25 à 17 09 51](https://user-images.githubusercontent.com/14292474/155748838-e3122ba5-16dc-47fe-ac2e-f673fcb38f7c.png)

Version details:
```
    "react": "17.0.2",
    "react-native": "0.65.2",
    "react-native-zohosalesiq-mobilisten": "4.2.6",
```

Thanks in advance for your help

**Comment by Angu-G** [comment]
Hello @MelanieJourne, Thanks for reporting. We will have this fixed and roll out an update which can be expected in a couple of days. We will notify you in the same thread.

**Comment by Angu-G** [comment]
Hi @MelanieJourne, Thanks for your patience. We have rolled out the fix in version [v4.2.7](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.7). Kindly upgrade to it and let us know.

**Comment by MelanieJourne** [comment]
Hello @Angu-G ,

I can confirm that I no longer have that issue when adding the mail. However, on some smartphone, we have the following error :
<img width="843" alt="Capture d’écran 2022-03-11 à 09 41 20" src="https://user-images.githubusercontent.com/14292474/157832742-262a78c0-b0b2-4c13-a8ed-49f02b8f5610.png">


Smartphone Brand : Xiaomi
Model : M2007J17G

**Comment by Angu-G** [comment]
Hello @MelanieJourne, Hope the latest [version](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.8) released is useful to sort out the reported issue. Let us know if you need further assistance. Thanks.
