### ISSUE TITLE
After end chat "Skip" should be ignore send feedback.

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#39]
![Screen Shot 2022-02-28 at 16 33 47](https://user-images.githubusercontent.com/7411097/155959348-900972dc-aeb0-4b21-8079-b6766d07d958.png)

When click Skip, It's popup the box for input the feedback. Maybe it should be ignore is reasonable.

**Comment by Rishabh-Raghunath** [comment]
We understand and agree with your concern.
We are currently working on improving this user interface.

We shall keep posted here once the update is rolled out.

**Comment by bhahirathan-mb-11956** [comment]
Hi @dieptang ,

Greeting! Thank you for your patience.

We are pleased to inform you that our feedback system has recently improved. As a part of this enhancement, you can set the [Chat.showFeedbackAfterSkip](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-show-feedback-after-skip.html)API to 'false' and check its result.

Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Best regards,
Bhahirathan M.
