### ISSUE TITLE
Unsupported modules detected: Android

### ISSUE THREAD

**Issue by RageOfJustice** [zoho/SalesIQ-Mobilisten-ReactNative#4]
When I open Android Studio the message appears in my Event Log

`Unsupported Modules Detected: Compilation is not supported for following modules: react-native-zohosalesiq-mobilisten. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project`

**Comment by Angu-G** [comment]
@RageOfJustice Please add our maven repository in your project's build.gradle file which is mentioned as step 3 in the [installation doc](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-installation.html) and sync the project. Please take a look into [this](https://stackoverflow.com/questions/28668252/android-studio-error-unsupported-modules-detected-compilation-is-not-supported) as well.
