### ISSUE TITLE
Sometime, ZohoSalesIQ.setLauncherVisibility(false) is not working

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#40]
When play a while with open the chat and close multiple time, I saw this strange behaviour. I added an event with
```
ZohoSalesIQ.addEventListener(ZohoSalesIQ.EVENT_CHAT_CLOSED, () => {
console.log('chat closed');
        ZohoSalesIQ.setLauncherVisibility(false);
      });
```
and trigger when I closed the chat, the function is triggered with ZohoSalesIQ.setLauncherVisibility(false); , but the launcher still display.

But when I add the button with onclick() => {ZohoSalesIQ.setLauncherVisibility(false)} then it working. 

I am using "react-native": "^0.67.2" and "react": "^17.0.2".
Many thanks

**Comment by Rishabh-Raghunath** [comment]
This issue is now being marked as closed. 
Please feel free to get back to us in case you have further queries.
Thanks.
