### ISSUE TITLE
Could not find method compile()

### ISSUE THREAD

**Issue by MatiasWettstein** [zoho/SalesIQ-Mobilisten-ReactNative#43]
Hello, i have an issue when i run my app 
![image](https://user-images.githubusercontent.com/51135740/169875389-af2e4b4f-7cf0-427f-85ca-a6508320a607.png)
I'm ussing OpenJDK11 and gradle 7.3.3

If someone could fix it, I would appreciate if can tell me how

**Comment by wditechy** [comment]
node_modules/react-native-zohosalesiq-mobilisten/android/build.gradle

compile 'com.facebook.react:react-native:+' failed, need to change implementation, 

Please fix this in next version

**Comment by zahidahmed024** [comment]
i also have this same issue . 
gradle 7.3.3

any updates on how to solve it ?

**Comment by Rishabh-Raghunath** [comment]
We are currently working on pushing an update that addresses this issue.
We will keep posted here once we have the update rolled out live soon.

**Comment by wditechy** [comment]
Thank you @Rishabh-Raghunath

**Comment by DavidBhahirathan** [comment]
Hi @zahidahmed024, 

Thank you for your patience. This issue has been addressed in our latest version [version(v4.2.10](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v4.2.10)). 

For further queries, please feel free to write us at [support@zohosalesiq.com]. We will be happy to assist you. 

Regards,
Bhahirathan

**Comment by MatiasWettstein** [comment]
thanks you! @DavidBhahirathan
