### ISSUE TITLE
ZohoSalesIQ.setThemeColorforiOS not updating the colour of SalesIQ chat launcher

### ISSUE THREAD

**Issue by Roundups** [zoho/SalesIQ-Mobilisten-ReactNative#46]
Hi we are using the package with an expo app, we use eas custom config under the hood for the integration to work. We are using the latest version 4.2.10. Other functions work such as setChatTitle and initWithCallback.

I have attempted deleting and re-installing the app but I have not been able to alter the colour. I hope I am making a silly error.

Thanks

**Comment by Venkatesh-iOS** [comment]
Hi,

The "setThemeColorforiOS" API is intended to be used right at the time of initialization. If the API is invoked after initialization is complete, there is a chance that the theme color may not be applied throughout the UI.

Here is an example code snippet for reference;
`
import { Platform } from 'react-native';
import { ZohoSalesIQ } from 'react-native-zohosalesiq-mobilisten';

var appKey;
var accessKey;

if (Platform.OS === 'ios') {
    appKey = "ios_appKey";
    accessKey = "ios_accessKey";
} else {
    appKey = "android_appKey";
    accessKey = "android_accessKey";
}

ZohoSalesIQ.initWithCallback(appKey, accessKey, (success) => {
    if (success) {
         // initialization successful     
    } else {
        // initialization successful failure
    }
});
ZohoSalesIQ.setThemeColorforiOS(#colorCode)`

We request you to try this out and let us know if all works fine for you.
If the issue persists, please feel free to mail us at (support@zohosalesiq.com) along with the Github issue ID.

Regards, 
Venkatesh
Zoho SalesIQ

**Comment by Roundups** [comment]
Ah thank you! Maybe this can be added to the documentation?

I will close the issue.

**Comment by ubaidkolad** [comment]
> Hi we are using the package with an expo app, we use eas custom config under the hood for the integration to work. We are using the latest version 4.2.10. Other functions work such as setChatTitle and initWithCallback.
> 
> 
> 
> I have attempted deleting and re-installing the app but I have not been able to alter the colour. I hope I am making a silly error.
> 
> 
> 
> Thanks

Hey @Roundups - I'm trying to integrate this in my expo app. Can you please share a structure or steps how did you integrate it in the expo app or maybe the custom config file? Thanks in advance!
