### ISSUE TITLE
Directly open Knowledgebase tab instead of Conversations

### ISSUE THREAD

**Issue by Ramanpreet6262** [zoho/SalesIQ-Mobilisten-ReactNative#48]
I am using RN SDK for our Android app.

Version
`"react-native-zohosalesiq-mobilisten": "4.2.10"`

So wanted to know if there is a way out by which I can directly open the knowledgebase tab instead of conversations on click of a custom button from my App.

Any of these solutions work:
- Opening knowledge base tab directly?
- Reordering bottom tabs with knowledgebase first and then conversations

I am not able to find any such method in docs, can you please help me in knowing if this is possible?

Thanks.

**Comment by DavidBhahirathan** [comment]
Hello @Ramanpreet6262!

Greetings from the Zoho SalesIQ team,

Please find the solutions to your requirements below,

*1*. Opening Knowledge-base directly:
__Option A__: For this requirement, you may hide the conversations tab within Mobilisten using the [setConversationVisibility](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-conversation-visibility.html) API. Invoking this API with the param as `false` would result in the conversations tab behind hidden and would open the Knowledge-base tab directly.

*Note*: Your users would still be able to initiate support conversations from the knowledge-base tab via the floating chat button that will be present.

__Option B__: You can create a custom button on the sections/screens in which you want the knowledge base to be displayed and then open the knowledge based on the click of the custom button without opening the conversation.
Mobilisten provides APIs that allow you to fetch the list of articles that are available. Please find the documentation for the same [here](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-faq-v2.html).

If a user selects/taps on a specific article, you may invoke the [openArticle](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-open-article.html) API which would open the article directly if provided the article ID.
This option gives you more power in terms of customization but requires some upfront work.

*2*. Reordering tabs (Having the Knowledge-base tab first followed by Conversations):
At this moment it is not possible to reorder the bottom tabs in mobile SDK. However, we have forwarded this request to our product management team.

Feel free to write to us for further assistance.

Regards, 
Bhahirathan M

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 ,

We have added a new [API](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-tab-order.html) to change the order of the Mobilisten bottom navigation tabs. Please check out version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.0.0).

Regards,
Bhahirathan M,
Zoho SalesIQ.
