### ISSUE TITLE
Android notification not pushing when the app on the background.

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#50]
Hi, 

Few month ago I config and setup everything for SaleIQ and it's working. 
Recently I saw the notification for android device no longer popup when I closed the app totally. It;s only working when I open my App and leave it. (IOS still works fine).

My notification from mainly function still works fine when I closed the app on the background. Only saleIQ is not.

I double checked all settings from url: https://www.zoho.com/salesiq/help/developer-guides/android-mobile-sdk-installation-2.0.html and I don't see any facing problem of that.

![Screen Shot 2022-08-25 at 17 36 08](https://user-images.githubusercontent.com/7411097/186643309-508c005b-f0f2-4029-8259-ea857ce1ea6e.png)

Any hints that I can make it working again?

**Comment by dieptang** [comment]
`
public class MyFirebaseMessagingService extends FirebaseMessagingService {
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage)
    {
        Map extras = remoteMessage.getData();                                
        RNZohoSalesIQ.handleNotification(MainApplication.getApplication(),extras);
    }

    @Override
    public void onNewToken(String token) {
        String refreshedToken =FirebaseInstanceId.getInstance().getToken();
        RNZohoSalesIQ.enablePush(refreshedToken,--true/false--);
        //Pass true to test push notification from SalesIQ console which is explained in Step 6

    }
}`

I found something interesting, Is it need for React Native from Java class? If it is need, can you send me the full example like importing FirebaseMessagingService, how to handle it?

**Comment by DavidBhahirathan** [comment]
Hi @dieptang ,

Thanks for reaching out to us. We're glad to know your interest in Mobilisten react-native. Please ensure you have completed the following steps,

1. Add your project in firebase with all the given steps - [documentation](https://firebase.google.com/docs/android/setup)
2. Add FCM to your project - [documentation](https://firebase.google.com/docs/cloud-messaging/android/client)
3. Finally, ensure mobilisten push messages are handled properly as given sample snippet below:

```

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
import com.zohosalesiq.reactlibrary.RNZohoSalesIQ;

import java.util.Map;

public class MyFirebaseMessagingService extends FirebaseMessagingService {

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage)
    {
        Map extras = remoteMessage.getData();
        
        //       Please pass the application context for the first param
        RNZohoSalesIQ.handleNotification(MainApplication.getApplication(), extras);
    }

    @Override
    public void onNewToken(String token) {    
        RNZohoSalesIQ.enablePush(token,true);
        //Pass true to test push notification from SalesIQ console which is explained in Step 6

    }
}
```

Note: The google-services.json file and  FCM server key must be taken from the same firebase project.

I hope this helps. Feel free to write us at (support@zohosalesiq.com) along with your Github ID for further assistance.

Regards,
Bhahirathan.

**Comment by DavidBhahirathan** [comment]
Hi @dieptang,

We are sorry for the inconvenience. We need to debug further on your push notification setup/configuration with the project to find the issue.

Could you please contact our support team at support@zohosalesiq.com, along with your GitHub ID, for further assistance?

Regards,
Bhahirathan M.

**Comment by dieptang** [comment]
Yes, I sent from SalesIQ dashboard already, nothing happing. Please try to debug on yourself.

**Comment by DavidBhahirathan** [comment]
Hi @dieptang,

Sorry for the inconvenience. We have checked the push notifications from our side, and it's working correctly. We need to debug from our side with your project to identify the cause of the issue. 

So please contact our support team at [support@zohosalesiq.com] with your portal name, and chat details used for push notification testing like chat IDs(starting with #). We will be happy to assist you.

Regards,
Bhahirathan M.

**Comment by dieptang** [comment]
> Hi @dieptang,
> 
> Sorry for the inconvenience. We have checked the push notifications from our side, and it's working correctly. We need to debug from our side with your project to identify the cause of the issue.
> 
> So please contact our support team at [[support@zohosalesiq.com](mailto:support@zohosalesiq.com)] with your portal name, and chat details used for push notification testing like chat IDs(starting with #). We will be happy to assist you.
> 
> Regards, Bhahirathan M.

Can you send me the video? Please make sure on android, your application closed on the background, and send the chat.

This is video from our side:

https://drive.google.com/file/d/1CnxQPEMxe13iDaINrxbV4dlzFEcuiboS/view?usp=sharing

**Comment by DavidBhahirathan** [comment]
Hi @dieptang,

Please find the screen recording attachment link of the sample push notification working in both background and killed state.

link: https://workdrive.zohoexternal.com/file/8moeva8c22a87811847daa327c8d8c7c2611e

Regards,
Bhahirathan M.

**Comment by dieptang** [comment]
Hi @DavidBhahirathan

Thank you so much, I recheck again line by line and found problem from ourside with the getApplicationContext() function was return null.

The problem is solved!
