### ISSUE TITLE
Add typescript support

### ISSUE THREAD

**Issue by arthedza** [zoho/SalesIQ-Mobilisten-ReactNative#51]

**Comment by Ramanpreet6262** [comment]
+1 to this, getting TS error on importing Zoho SalesIQ in my TS project for missing .d.ts files

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 
Sorry for the inconvenience. We will check this and update you. 
Thanks.

**Comment by oismaelash** [comment]
Any update about this topic ?

**Comment by DavidBhahirathan** [comment]
Hi @oismaelash ,

Sorry for the inconvenience. We have the plans to support typescript soon in the upcoming builds and will take this up based on the priority. Please bear with us in the meantime.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @arthedza , @Ramanpreet6262 , @oismaelash ,
 
We have supported typescript in our Mobilisten React Native SDK. Kindly update the SDK to the [latest version](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/latest) and verify it once.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.
