### ISSUE TITLE
I need an event callback after openChat()

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#52]
Hi,

We have the button and trigger the function ZohoSalesIQ.openChat(); when the user click on this. But sometime for new installing users had to waiting about 5 seconds for popup the chat windows. Can you please add the event after the chat windows popup?

For example:

ZohoSalesIQ.openChat();

and then

ZohoSalesIQ.isChatOpened(() => 
   {
        console.log('Chat windows is opening');
  });

Thank you.

**Comment by DavidBhahirathan** [comment]
Hi @dieptang ,

Thanks for reporting us. We'll consider your query and implement this in the upcoming release.

Regards,
Bhahirathan M.

**Comment by DavidBhahirathan** [comment]
Hi @dieptang ,

Thanks for your patience. The above requirement has been handled in the latest update with the EVENT_CHATVIEW_OPENED event in the [event listener](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-add-event-listener.html). Please check out version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.0.0).

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @dieptang,
 
We have supported a new API [ZohoSalesIQ.present()](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-present.html) to open our SDK which gives you the callback. Please have a look at this if needed.
 
Regards,
Bhahirathan M
Zoho SalesIQ.
