### ISSUE TITLE
java.lang.NullPointerException (com.facebook.react.bridge.CallbackImpl.invoke)

### ISSUE THREAD

**Issue by Ramanpreet6262** [zoho/SalesIQ-Mobilisten-ReactNative#56]
Hi team,
We got this stack trace on firebase crashlytics

<img width="1108" alt="Screenshot 2022-10-20 at 11 00 23 AM" src="https://user-images.githubusercontent.com/28749866/196864030-3c61259d-be17-478c-bdcc-501f5dd9eaf2.png">

And stack trace for the same issue from play store console

`Exception java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
  at com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:26)
  at com.zohosalesiq.reactlibrary.RNZohoSalesIQ$56.onInitError (RNZohoSalesIQ.java:980)
  at com.zoho.livechat.android.api.GetAndroidChannel.run (GetAndroidChannel.java:276)`
  
- Happening on Android
- React Native version `"0.66.4"`
- SDK Version `"react-native-zohosalesiq-mobilisten": "4.2.10"`

**Comment by Ramanpreet6262** [comment]
This got reported on sentry as well, stack trace:

<img width="838" alt="Screenshot 2022-10-20 at 12 27 17 PM" src="https://user-images.githubusercontent.com/28749866/196877930-715bf559-bdfd-4c69-ac8b-1c41ec405d1f.png">

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262,

Thanks for writing us. Sorry for the inconvenience. We'll check this and update you shortly. 

Regards,
Bhahirathan M.

**Comment by Ramanpreet6262** [comment]
@DavidBhahirathan Any update here? This issue is being reported often on sentry.

**Comment by Ramanpreet6262** [comment]
@DavidBhahirathan Any update here?

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 ,

The above crash has been fixed in version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.0.0).

Regards,
Bhahirathan M,
Zoho SalesIQ.
