### ISSUE TITLE
Invariant Violation crash on debug builds

### ISSUE THREAD

**Issue by Ramanpreet6262** [zoho/SalesIQ-Mobilisten-ReactNative#57]
Facing the below issue while running the app in debug mode (sometimes, when we reload the app and sometimes on init)

<img width="836" alt="Screenshot 2022-10-20 at 11 26 25 AM" src="https://user-images.githubusercontent.com/28749866/196867504-4ff03ec7-65b1-4f34-a314-b642b0d33d66.png">

Here the value of cbID and callID keeps on changing rest same.

- Happening on Android
- React Native version `"0.66.4"`
- SDK Version `"react-native-zohosalesiq-mobilisten": "4.2.10"`

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 ,

Thanks for writing us. Sorry for the inconvenience. We'll check this and update you shortly. 

Regards,
Bhahirathan M

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 ,

The above crash has been fixed in version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.0.0).

Regards,
Bhahirathan M,
Zoho SalesIQ.
