### ISSUE TITLE
UnsupportedOperationException in LiveChatUtil.showFeedbackDialog

### ISSUE THREAD

**Issue by nillion** [zoho/SalesIQ-Mobilisten-ReactNative#59]
Getting crashes on version 4.2.10

<img width="1374" alt="Screenshot 2022-11-24 at 2 54 11 PM" src="https://user-images.githubusercontent.com/10284004/203746485-c63cea9d-90d7-4ded-ade3-ac8e22a810d1.png">

- Platform: Android
- SDK Version: 4.2.10

**Comment by DavidBhahirathan** [comment]
Hi @nillion ,

Thank you for writing to us. We'll look into this crash and update you here once it is fixed. 

Regards,
Bhahirathan M.

**Comment by DavidBhahirathan** [comment]
Hi @nillion ,

Thank you for your patience. We have fixed this issue. We recommend you update to the latest version [6.1.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v6.1.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.
