### ISSUE TITLE
java.lang.NullPointerException (com.zoho.livechat.android.utils.AudioSeekbarHandler.getListener)

### ISSUE THREAD

**Issue by Ramanpreet6262** [zoho/SalesIQ-Mobilisten-ReactNative#60]
Hi, we are facing this crash if the user changes the position of slider quickly in the audio message type in the chat window.

**Firebase stack trace:**

<img width="979" alt="image" src="https://user-images.githubusercontent.com/28749866/204974943-03a30cc7-8287-4e15-9f83-57e66bfbd3ff.png">

**Sentry stack trace:**

<img width="826" alt="image" src="https://user-images.githubusercontent.com/28749866/204975038-878d804e-f18e-4726-8d1d-f8a005776ed8.png">

- Happening on Android
- React Native version `"0.66.5"`
- SDK Version `"react-native-zohosalesiq-mobilisten": "4.2.10"`

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 ,

Thank you for writing to us. We'll look into this crash and update you here once it is fixed. 

Regards,
Bhahirathan M.

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262  ,

This issue has been fixed. Please update to the version [5.1.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.1.0) and verify once. Please write back to us if the issue persists.

Regards,
Bhahirathan M,
Zoho SalesIQ.
