### ISSUE TITLE
java.lang.NullPointerException (com.zoho.livechat.android.utils.LiveChatUtil.isStartChatEnabled)

### ISSUE THREAD

**Issue by Ramanpreet6262** [zoho/SalesIQ-Mobilisten-ReactNative#62]
Hi, we are getting reports of this crash on firebase crashlytics

**Stack trace:**

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/28749866/205856094-cadfe507-728c-408a-a820-8657a2478e10.png">

- Happening on Android
- React Native version `"0.66.5"`
- SDK Version `"react-native-zohosalesiq-mobilisten": "4.2.10"`

**Comment by DavidBhahirathan** [comment]
Hi @Ramanpreet6262 ,

The above crash has been fixed in version [5.0.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.0.0).

Regards,
Bhahirathan M,
Zoho SalesIQ.
