### ISSUE TITLE
Issue with startChat() method.

### ISSUE THREAD

**Issue by callmemonky** [zoho/SalesIQ-Mobilisten-ReactNative#63]
Hi,

I am facing an issue with the startChat method.

When I'm invoking the startChat method multiple times, it sometimes takes me back to the old chat instance instead of the new chat instance.

New chat instance is created but old chat instance is opened first and we get a notification for the new one.

Issue Video - 

"react-native-zohosalesiq-mobilisten": "4.2.10"
"react": "17.0.2"
"react-native": "0.66.5"

Device Name - OnePlus Nord 2 5G
Operating System: OxygenOS 11.3 (based on Android™ 11)
CPU: MediaTek Dimensity 1200-AI
GPU: ARM G77 MC9
RAM: 6GB

https://user-images.githubusercontent.com/25193916/206711120-85d5b1d6-e65e-4468-a25c-28a5f63fd479.mp4

**Comment by DavidBhahirathan** [comment]
Hi @callmemonky ,

Thanks for writing to us. We'll look into this issue and update here once fixed. Meanwhile, please check out the [latest version](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/latest).

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by DavidBhahirathan** [comment]
Hi @callmemonky ,

This issue has been fixed. Please update to the version [5.1.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v5.1.0) and verify once. Please write back to us if the issue persists.

Regards,
Bhahirathan M,
Zoho SalesIQ.
