### ISSUE TITLE
Unable to build android app

### ISSUE THREAD

**Issue by dsound-zz** [zoho/SalesIQ-Mobilisten-ReactNative#64]
We're trying to implement Zoho SalesIQ chat widget in our app. We have it working on web and ios but not Android. We've followed the docs: 

https://www.zoho.com/salesiq/help/developer-guides/android-mobile-sdk-installation-2.0.html

The error on android build is:

`error: lambda expressions are not supported in -source 7`

Here's a screen shot:

<img width="1051" alt="Screen Shot 2022-12-22 at 11 42 15_copy" src="https://user-images.githubusercontent.com/6018146/209175987-9674aa55-5b9a-4cd9-8fde-f3a86b787c42.png">

"react-native": "0.67.5",
 "react-native-zohosalesiq-mobilisten": "^4.2.17",
running openjdk 11.0.17 locally

At first we thought it was an issue with linking but react-native says that manual linking is not required after version 5.9. 

Is it a Java issue?

**Comment by globerSaru37** [comment]
Having the same issue, already tried installing with npm + link and yarn. iOS works fine but Android build crashes just like in SS.

**Comment by globerSaru37** [comment]
@dsound-zz In case it helps, we just tried building Android with version 4.2.14 and it works smoothly. 

Maybe something went wrong with the latest release (?)

**Comment by DavidBhahirathan** [comment]
Hi @dsound-zz and @globerSaru37 ,

Thanks for writing to us. 
```
lambda expressions are not supported in -source 7

(use -source 8 or higher to enable lambda expressions)
```
The above error states that your react-native android project is using JDK 7. So, please upgrade the JDK to version 8 or above to resolve this issue.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by gabrielkabral** [comment]
@DavidBhahirathan Actually the project has the JDK 8. I tried with the new release 5.0.0 and got the same error.

The only way that I'm able to run Android here, after 4.2.14, is adding these lines in `node_modules/react-native-zohosalesiq-mobilisten/android/build.gradle`

``` 
compileOptions {
   sourceCompatibility JavaVersion.VERSION_1_8
   targetCompatibility JavaVersion.VERSION_1_8
}
 ```

My `app/build.gradle` already have this config.
