### ISSUE TITLE
openChat() not working on iOS

### ISSUE THREAD

**Issue by MelanieJourne** [zoho/SalesIQ-Mobilisten-ReactNative#65]
Hello,

I am using this sdk for more than a year and recently I discover that my chat button is not working on iOS anymore
Everything is working fine on Android.

I use the following function in that order:
`ZohoSalesIQ.initWithCallback` => Callback tells me it is a success
`ZohoSalesIQ.isChatEnabled` => Callback tells me it is enabled
`ZohoSalesIQ.openChat` => I called this function when my user clicks on my custom button but nothing happens

Tested on the following device : 
iPhone SE - iOS 16.0
iPhone 13 - iOS 16.3.1
iPhone XS - iOS 16.3

My version of the package:
`"react-native-zohosalesiq-mobilisten": "4.2.17"`
I upgrade to: 
`"react-native-zohosalesiq-mobilisten": "5.1.0"`
**But problem still persists**

Here my version of RN
```
    "react": "18.0.0",
    "react-native": "0.69.7",
```

Do you have any idea of what could cause this issue ?

Kind regards

**Comment by MelanieJourne** [comment]
After further testing, it is not working on iOS 14.8 either

**Comment by Venkatesh-iOS** [comment]
Hello @MelanieJourne  ,

Thank you for your patience, Above mentioned issue has been fixed. Please upgrade to version 5.2.0 and check once.
If the issue persists, feel free to mail us at (support@zohosalesiq.com).

Regards,
Venkatesh
Zoho SalesIQ.
