### ISSUE TITLE
ZohoSalesIQ.setThemeColorforiOS() and ZohoSalesIQ.setThemeColorforAndroid() are not functioning in React Native

### ISSUE THREAD

**Issue by waseemViwell** [zoho/SalesIQ-Mobilisten-ReactNative#67]
The ZohoSalesIQ.setThemeColorforiOS() and  ZohoSalesIQ.setThemeColorforAndroid()  function, which is used to set the theme color for Zoho SalesIQ in iOS and Android apps built using React Native, is not functioning as expected. When attempting to set a theme color using this function, the color does not update in the Zoho SalesIQ interface.
Steps to Reproduce:

1. Create a React Native app with Zoho SalesIQ integration.
2. Attempt to set a theme color using the ZohoSalesIQ.setThemeColorforiOS() or ZohoSalesIQ.setThemeColorforAndroid()   function in ios and Android respectively.
3. Observe that the color does not update in the Zoho SalesIQ interface.

Expected Behavior:
The ZohoSalesIQ.setThemeColorforiOS() and ZohoSalesIQ.setThemeColorforAndroid() functions should set the theme color for Zoho SalesIQ in iOS and Andriod apps built using React Native, and the color should update in the Zoho SalesIQ interface.

Actual Behavior:
The ZohoSalesIQ.setThemeColorforiOS()  and ZohoSalesIQ.setThemeColorforAndroid()  function is not functioning as expected, and the color does not update in the Zoho SalesIQ interface.

Environment:
React Native version: 0.68.2
Zoho SalesIQ SDK version: 5.2.0
iOS version: 16.2
Android Version: 12
Device: any IOS or Android

<img width="424" alt="Screen Shot 2023-04-07 at 3 45 54 PM" src="https://user-images.githubusercontent.com/130146832/230595976-0d242552-a9b3-4b80-b662-03c0763e2253.png">

**Comment by waseemViwell** [comment]
Hi David, thank you so much for your kind response. yes, For iOS, the .setThemeColorforiOS() API is functional, but i was looking to change the background color as well in IOS. can you please guide me on this?
Thanks
________________________________

**Comment by Venkatesh-iOS** [comment]
Hi @waseemViwell 

As of now, we do not have support for customizing background colors. However, we have plans to add UI customization support in the future, though we do not have a confirmed timeline at the moment. Rest assured, you will be notified when this feature becomes available for use and when the new version is released. Thank you for your understanding.

Regards,
Venkatesh
Zoho SalesIQ.
