### ISSUE TITLE
Knowledge base shows something went wrong - iOS

### ISSUE THREAD

**Issue by Md-Mudassir47** [zoho/SalesIQ-Mobilisten-ReactNative#69]
For some reason the knowledge base is not loading in iOS, works fine in Android. Also the default color accent of the chat bubble is iOS is very odd.. how can i change that?

![Simulator Screen Shot - iPhone 14 - 2023-04-19 at 12 40 54](https://user-images.githubusercontent.com/85115578/233000950-9204f304-97d2-4d4b-92db-75c69a5b0197.png)

**Comment by Md-Mudassir47** [comment]
using `"react-native-zohosalesiq-mobilisten": "^5.2.0",`

**Comment by Venkatesh-iOS** [comment]
Hello @Md-Mudassir47 ,

Thank you for reaching out to us. We appreciate your interest in our SalesIQ Mobilisten React Native application.

Regarding your question about the chat bubble theme color, you can change it using the [.setThemeColorforiOS()](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-set-chat-theme-ios.html) API.

If you have any issues related to our Knowledge Base, we recommend contacting our support team at support@zohosalesiq.com. They will be more than happy to assist you.

Thank you for choosing Zoho SalesIQ as your preferred messaging platform.

Best regards,
Venkatesh
Zoho SalesIQ.
