### ISSUE TITLE
Could not resolve dependency while installing

### ISSUE THREAD

**Issue by arinconc** [zoho/SalesIQ-Mobilisten-ReactNative#7]
I'm installing with the command:
`npm install react-native-zohosalesiq-mobilisten --save`

And npm gives me the error:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react-native @ "^ 0.41.2" from react-native-zohosalesiq-mobilisten@1.3.5
npm ERR! node_modules / react-native-zohosalesiq-mobilisten
npm ERR! react-native-zohosalesiq-mobilisten @ "*" from the root project
```
Can someone guide me to install the library
Greetings,
Antonio

**Comment by Angu-G** [comment]
Hello @arinconc, Can you please share us with the **npm** version and **react-native** versions used in your project so that it will be helpful for us to debug?

**Comment by arinconc** [comment]
My npm version is 7.0.8,
And these are my dependencies in the package.json"dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/progress-bar-android": "^1.0.4",
    "@react-native-community/progress-view": "^1.2.3",
    "@react-native-community/toolbar-android": "^0.1.0-rc.2",
    "@react-native-firebase/analytics": "^7.6.9",
    "@react-native-firebase/app": "^8.4.7",
    "@react-native-firebase/auth": "^9.3.2",
    "@react-native-firebase/firestore": "^7.9.1",
    "@react-native-firebase/functions": "^7.4.10",
    "@react-native-firebase/in-app-messaging": "^7.5.8",
    "@react-native-firebase/messaging": "^7.9.2",
    "@react-native-firebase/remote-config": "^9.0.12",
    "@react-native-firebase/storage": "^7.4.11",
    "@react-navigation/native": "^5.8.5",
    "@react-navigation/stack": "^5.12.2",
    "i18n-js": "^3.7.1",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-moment": "^1.0.0",
    "react-native": "^0.63.3",
    "react-native-android-open-settings": "^1.3.0",
    "react-native-camera": "^3.40.0",
    "react-native-device-info": "^6.2.0",
    "react-native-geolocation-service": "^5.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-localize": "^1.4.3",
    "react-native-vector-icons": "^7.1.0",
    "react-native-webview": "^10.10.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
},

**Comment by arinconc** [comment]
Is there any news?

Thanks @Angu-G !!

**Comment by Angu-G** [comment]
@arinconc, Thank you for your patience. Can you please try our latest version [v1.4.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/1.4.0) and let us know you still face this issue.

**Comment by arinconc** [comment]
> @arinconc, Thank you for your patience. Can you please try our latest version [v1.4.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/1.4.0) and let us know you still face this issue.

@Angu-G This is the result while installing the library in a empty project:
`npm install react-native-zohosalesiq-mobilisten@1.4.0 --save`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: salesiq@0.0.1
npm ERR! Found: react-native@0.63.3
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-zohosalesiq-mobilisten@1.4.0
npm ERR! node_modules/react-native-zohosalesiq-mobilisten
npm ERR!   react-native-zohosalesiq-mobilisten@"1.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/---/.npm/eresolve-report.txt for a full report.
```
And this is my packages.json:
```
{
  "name": "salesiq",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.13.1",
    "react-native": "0.63.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Thank you very much for your help!
Antonio

**Comment by Angu-G** [comment]
@arinconc, Thank you for your patience. We have rolled out an update (v1.4.1) for the latest RN version. Please try now and let us know the status.

**Comment by Rishabh-Raghunath** [comment]
Hi @arinconc, we have updated our **react-native** peer dependency for the module now with version [**1.4.1**](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v1.4.1).
This should hopefully resolve the issue you are having with resolving dependencies using npm 7.
Requesting you to perform an update and let us know if this resolves it.

**Comment by arinconc** [comment]
Now it installs without problems.
Thanks for the attention.

> Hi @arinconc, we have updated our **react-native** peer dependency for the module now with version [**1.4.1**](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v1.4.1).
> This should hopefully resolve the issue you are having with resolving dependencies using npm 7.
> Requesting you to perform an update and let us know if this resolves it.

**Comment by Rishabh-Raghunath** [comment]
That's great. Closing this issue.
