### ISSUE TITLE
Opening the chat from notification and then going back closes the app

### ISSUE THREAD

**Issue by Md-Mudassir47** [zoho/SalesIQ-Mobilisten-ReactNative#71]
Is there a way to handle the stack to go back to homescreen when opened the chat from notification? 
Currently it works fine if i open the chat bubble on homescreen and press the back button it goes back to homescreen but when i'm using the app and i get a chat notification and i open the notification in app which opens the chat screen and then I try to go back it closes the app. 

https://user-images.githubusercontent.com/85115578/233319302-937236a9-cfc7-4f23-a931-b9731cedafa5.mov

Using: `  "react-native-zohosalesiq-mobilisten": "^5.2.0",`

**Comment by DavidBhahirathan** [comment]
Hi @Md-Mudassir47 ,

Thanks for writing to us. We'll look into this issue and update you here once resolved.

Best regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by DavidBhahirathan** [comment]
Hi @Md-Mudassir47 ,

Thank you for your patience. We have fixed this issue. We recommend you update to the latest version [6.1.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v6.1.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.
