### ISSUE TITLE
1 duplicate symbol for architecture arm64 (iOS)

### ISSUE THREAD

**Issue by AdamLee321** [zoho/SalesIQ-Mobilisten-ReactNative#74]
<img width="444" alt="Screenshot 2023-10-16 at 12 56 43" src="https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/assets/22890658/fc434b43-e788-468f-a960-5bbe02a6b154">

Build Specifications
• react-native: 0.72.1
• xcode : 14.3.1
• React : 18
• react-native-zohosalesiq-mobilisten : ^6.1.1

Followed the installation steps at: https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-installation.html. I am receiving this error once I try to build the project. Has anyone encountered this issue? If so any solution?

**Comment by Venkatesh-iOS** [comment]
Hi @AdamLee321 

Greetings from Zoho SalesIQ. We have checked the above-provided build specifications and successfully built the project without encountering the 'duplicate symbol' error. Our 'mobilisten' dependency is also working as expected. If you're still facing this issue,  please don't hesitate to contact us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to help you. 

Best Regards,
Venkatesh,
Zoho SalesIQ

**Comment by AdamLee321** [comment]
Hi @Venkatesh-iOS, 

I have looked into this more and have noticed that there is a conflict with another library that I am using. 

`duplicate symbol '_hasListeners' in:
    /Users/adamlee/Library/Developer/Xcode/DerivedData/Randox-ecsjvxgjogoyadatjcdwjcilvgsz/Build/Products/Debug-iphonesimulator/RNAppleHealthKit/libRNAppleHealthKit.a(RCTAppleHealthKit.o)
    /Users/adamlee/Library/Developer/Xcode/DerivedData/Randox-ecsjvxgjogoyadatjcdwjcilvgsz/Build/Products/Debug-iphonesimulator/RNZohoSalesIQ/libRNZohoSalesIQ.a(RNZohoSalesIQ.o)` 

Would you know a possible solution to this issue? Unfortunately, I need to use both libraries so removing one is not a solution.
