### ISSUE TITLE
Use of undeclared identifier 'ZohoSalesIQ'

### ISSUE THREAD

**Issue by premsuthardev** [zoho/SalesIQ-Mobilisten-ReactNative#77]
i'm implement for ios but still not working (error in AppDelegate.m) (REACT_NATIVE)

#import <Mobilisten/Mobilisten.h>

[ZohoSalesIQ initWithAppKey: @"o0mYtfXUZp1XFoqzCLgZOF9xnx%2FFOoldhRTeZAlVeoYI4JOAhDXGjAg9ztf_in" accessKey:@"gxRtD2Tn3BT9ng2daRzGgCJWhShggClEyMN82wBwYZLf2iAVnqbEl0pDDzwgeFB7LKcIjoTEvVTBbRNgMONRGmHMTwgDQvS50Gg%3D%3D" completion:^(BOOL completed) { }];

error :: Use of undeclared identifier 'ZohoSalesIQ'

**Comment by venkatesh-ramesh-12517** [comment]
Hi @premsuthardev 

Thank you for reaching out. There might be an issue with the configuration. Please check our help guide on configuring React-Native Mobilisten and follow the instructions carefully to ensure a successful setup. 

If any issue persists, feel free to contact our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) for further assistance.

Best regards,
Venkatesh R,
Zoho SalesIQ.
