### ISSUE TITLE
Terminate chats with timer

### ISSUE THREAD

**Issue by tahahaz1374** [zoho/SalesIQ-Mobilisten-ReactNative#78]
Is it possible to terminate chat session after a certain amount of inactivity time,  eg. 5 minutes.

**Comment by bhahirathan-mb-11956** [comment]
Hi @tahahaz1374 ,

Thanks for writing to us. Yes, you can end the chat session after a certain amount of visitor's inactivity.

Please configure the following steps:

Settings -> Brands -> Select your brand -> Flow controls -> Idle chat handling -> Select the duration in `Close chats in` with a `Chat closing message` if needed.

If you face any issues, feel free to contact our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) for further assistance.

Regards, 
Bhahirathan M
Zoho SalesIQ.
