### ISSUE TITLE
enableScreenshotOption() not working on Android

### ISSUE THREAD

**Issue by vipsbpatel** [zoho/SalesIQ-Mobilisten-ReactNative#8]
I have integrated Zoho SaleIQ SDK and versioning information as per below:
```
dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.zoho.salesiq:mobilisten:2.3.2'
}

"react-native": "0.63.2",
"react-native-zohosalesiq-mobilisten": "^1.4.0",
```

```ZohoSalesIQ.enableScreenshotOption();```

When I choose "Take a screenshot" option, the app will close the chat window and I am not able to choose that option.

**Comment by Angu-G** [comment]
Hello @vipsbpatel, You will be shown the floating view in the middle of the device to capture the current screen or cancel the option. The floating view is not displayed Vipul?

**Comment by vipsbpatel** [comment]
Hi Angu-G,
I have clicked on attachment icon => Choose "Take a screenshot" option. After choosing option it will close the Chat window.
Please check attached video file link here.
https://www.dropbox.com/s/ch6ja2wjxxshr28/Screen%20Recording%202020-12-13%20at%2012.02.16%20PM.mov?dl=0

**Comment by Angu-G** [comment]
Hello @vipsbpatel, Thank you for your patience. We have tried reproducing on our end but no luck. Can you please share us your device model, RN version and portal name to debug further?

**Comment by Angu-G** [comment]
Hello @vipsbpatel, Can you please confirm whether you still face this issue?

**Comment by Angu-G** [comment]
@vipsbpatel, We are closing this issue. You can write back if you still face the issue. Thank you.
