### ISSUE TITLE
[Expo] : ReferenceError: Can't find variable: Platform to import ZohoSalesIQ

### ISSUE THREAD

**Issue by JoseEncinoza** [zoho/SalesIQ-Mobilisten-ReactNative#80]
Hi! I'm currently having this error trying to import ZohoSalesIQ:
```
ReferenceError: Can't find variable: Platform
```
![image](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/assets/29843909/465c4d0c-2873-4298-a1a5-61f20a55e6b3)

my Code :
```javascript
import { ZohoSalesIQ } from 'react-native-zohosalesiq-mobilisten';

ZohoSales = {

    setKeys: async function () {

        let appKey = "...";
        let accessKey = "...";

        ZohoSalesIQ.initWithCallback(appKey, accessKey, (success) => {
            if (success) {
                ZohoSalesIQ.setLauncherVisibility(true);
            } else {
                console.log("Zoho Error: no se cargo chat")
            }
        });
    },

    openChat: async function () {
        console.log("Zoho: Abrimos Chat")
        ZohoSalesIQ.openChat();
    }
}
export default ZohoSales;
```
After a trace, the error occurs right at the import of ZohoSalesIQ:
```javascript
import { ZohoSalesIQ } from 'react-native-zohosalesiq-mobilisten';
```
The message "ReferenceError: Can't find variable: Platform" refers to the file zohosalesiqJSWrapper.js in ./node_modules/react-native-zohosalesiq-mobilisten/components/. where it is using the following code in line 385:
```javascript
if (Platform.OS === 'android') {
  Dimensions.addEventListener('change', ({ window: { width, height } }) => {
    RNZohoSalesIQ.refreshLauncherPropertiesForAndroid();
  });
}
```
But it fails to get the Platform from react-native as it is not being imported in this file. 
By importing Platform into this file. works correctly!! 
```javascript
const { NativeModules, Dimensions, Platform } = require('react-native');    //No I18N
```

but I guess should not make this changes at the node_modules level.

thanks :)

Node: v18.17.0
npm: 9.6.7
packages:
"expo": "~50.0.5",
"react-native": "0.73.4",
"react-native-zohosalesiq-mobilisten": "^8.0.4",

**Comment by bhahirathan-mb-11956** [comment]
Hi @JoseEncinoza ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [8.0.5](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v8.0.5), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M
Zoho SalesIQ.
