### ISSUE TITLE
  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.zoho.livechat.android.models.SalesIQChat.getVisitid()' on a null object reference

### ISSUE THREAD

**Issue by ankitCompunnel** [zoho/SalesIQ-Mobilisten-ReactNative#89]
When start to chat adding all visitor's details like  visitor' name , email and phone in chat window app when it fails to connect to operator app crashes in android .

**Comment by bhahirathan-mb-11956** [comment]
Hi @ankitCompunnel,
 
We apologize for the inconvenience caused. We have fixed this issue in our current development build, which is in the testing phase and will be released soon. I'll keep you posted on the same regarding the updates.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by ankitCompunnel** [comment]
Thanks @bhahirathan-mb-11956  for your response.
Do let me know when it will be released because It is urgent issue and we have kept our project on hold due to this issue.

Regards,
Ankit

**Comment by bhahirathan-mb-11956** [comment]
Hi @ankitCompunnel,
 
The SDK build is currently in the QA testing phase and is planned for release this week.

**Comment by bhahirathan-mb-11956** [comment]
Hi @ankitCompunnel ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [9.2.0](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v9.2.0), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M,
Zoho SalesIQ.
