### ISSUE TITLE
Please reslove the issue ASAP

### ISSUE THREAD

**Issue by Anilfeker21** [zoho/SalesIQ-Mobilisten-ReactNative#92]
Reading env from: .env
Reading env from: .env.qa

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bharathkumar/Downloads/ANIL/DriverMobileApp/src_tinting/android/app/build.gradle' line: 264

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installEnvQaDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/bharathkumar/Downloads/ANIL/DriverMobileApp/src_tinting/android/app/build.gradle' line: 264

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'compile' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s

    at makeError (/Users/bharathkumar/Downloads/ANIL/DriverMobileApp/src_tinting/node_modules/execa/index.js:174:9)
    at /Users/bharathkumar/Downloads/ANIL/DriverMobileApp/src_tinting/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/bharathkumar/Downloads/ANIL/DriverMobileApp/src_tinting/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/bharathkumar/Downloads/ANIL/DriverMobileApp/src_tinting/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.

**Comment by bhahirathan-mb-11956** [comment]
Hi @Anilfeker21 ,
 
Thank you for reaching out to us. The given stack trace does not show an error relevant to Mobilisten. Please specify the issue or share the full stack trace so we can better assist you.
 
Additionally, we can see that something is causing the issue in your app/build.gradle file.
 
```
FAILURE: Build failed with an exception.

Where:
Build file '/Users/bharathkumar/Downloads/ANIL/DriverMobileApp/src_tinting/android/app/build.gradle' line: 264
```

If the issue persists, please contact us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to investigate this issue further for you.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.
