### ISSUE TITLE
Potential Issue with React Native Zoho SalesIQ Mobilisten v10.0.0 - registerVisitor must not be null

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#95]
Hello again! 😉

I believe there's an issue with the recent version. After updating my application to React Native Zoho SalesIQ Mobilisten v10.0.0 and React Native 0.71.19, it started crashing.

![image](https://github.com/user-attachments/assets/91f31135-746e-4170-9e92-ba9af31f9c1e)

On our end, we've already initialized the Zoho API and assigned the UserID using the following code:

`if (UserID){
            ZohoSalesIQ.registerVisitor(UserID);
        }`

Could you please double-check this? Thanks!

**Comment by venkatesh-ramesh-12517** [comment]
Hello @dieptang 

Thank you for reaching out to us. It appears the `completion` argument for the `registerVisitor` function is missing, which is required for proper functionality. Please refer to the documentation for further details: [documentation link](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-register-visitor.html).

If you have any other queries, feel free to contact us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com).

Regards,
Venkatesh R,
Zoho SalesIQ.

**Comment by dieptang** [comment]
Not, it's actually not NULL. Previous version it;s working fine. Only happening on recently version

**Comment by bhahirathan-mb-11956** [comment]
Hi @dieptang ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [10.0.1](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v10.0.1), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M
Zoho SalesIQ.
