### ISSUE TITLE
Android v.9.3.1 unregisterVisitor isn't working for Android

### ISSUE THREAD

**Issue by awais-wego** [zoho/SalesIQ-Mobilisten-ReactNative#96]
hey, Team!
I'm trying to unregister the visitor once the user logs out. It works fine on iOS, but it's not working on Android. After logging out, the user is still able to see their chat history. I want to clear the chat history once the user logs out.
Here is how I'm doing:
`ZohoSalesIQ.unregisterVisitor();`
Thanks in advance.

**Comment by bhahirathan-mb-11956** [comment]
Hi @awais-wego ,
 
We apologize for the inconvenience caused. We'll look into this issue and update you.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @awais-wego,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [10.0.2](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v10.0.2), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M
Zoho SalesIQ.
