### ISSUE TITLE
SDK 34: Incorrect package="com.zohosalesiq.reactlibrary" found in source AndroidManifest.xml

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#97]
Google recently required minimum SDK 34 for publish the application to Google Store. Your package last version will get the error: 

`Incorrect package="com.zohosalesiq.reactlibrary" found in source AndroidManifest.xml: /Users/flane/CODE/XXXX/node_modules/react-native-zohosalesiq-mobilisten/android/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported.
Recommendation: remove package="com.zohosalesiq.reactlibrary" from the source AndroidManifest.xml: /Users/flane/CODE/XXXX/node_modules/react-native-zohosalesiq-mobilisten/android/src/main/AndroidManifest.xml.`

You know what to do :D

**Comment by bhahirathan-mb-11956** [comment]
Hi @dieptang ,
 
We apologize for the inconvenience caused. We'll look into this issue and update you.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
Hi @dieptang ,

Thank you for your patience. We have fixed this issue. 

We recommend you update to the latest version [10.0.2](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v10.0.2), and verify. Please feel free to write back to us at (support@zohosalesiq.com) in case of any issues.

Regards,
Bhahirathan M
Zoho SalesIQ.
