### ISSUE TITLE
React Native APIs for iOS Push Notifications

### ISSUE THREAD

**Issue by AngadSethi** [zoho/SalesIQ-Mobilisten-ReactNative#98]
Hey,

So, I've been able to implement SalesIQ Push Notifications for [Android](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-mobile-push-notification-android.html)

However, I'm having a hard time doing the same thing for [iOS](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-mobile-push-notification-ios.html) because a lot of the methods used in the integration guide haven't been exposed over the bridge.

Can you folks please help me out?

**Comment by venkatesh-ramesh-12517** [comment]
Hi @AngadSethi 
 
Thank you for reaching out. The methods listed in the[ iOS push notification guide](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-mobile-push-notification-ios.html) are mandatory to ensure that notifications work correctly in your app. These methods handle essential functions like receiving and displaying notifications.
 
If certain methods are not available via the bridge, you may need to add them directly in the native iOS code and connect them to your React Native app.
 
Please ensure all the methods are implemented as per the guide to avoid any issues. 
If you need further assistance, please contact our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com).—we're here to help!
 
Regards,
Venkatesh R
Zoho SalesIQ.

**Comment by venkatesh-ramesh-12517** [comment]
Hi @AngadSethi 

To make the integration easier, we have a sample React Native project available that includes the necessary push notification methods for iOS. You can refer to these project to see how these methods are implemented directly in the native code: [Sample React Native Project](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/tree/master/example).
 
The implementation details, including push notification methods, are demonstrated in the AppDelegate.mm file of the sample project. You can check it here: [AppDelegate.mm File](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/blob/master/example/ios/mobilistensampleapp/AppDelegate.mm).
 
Please review these sample for guidance, and feel free to replicate the approach in your project.
 
If you need further assistance, please contact our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com).—we're here to help!
 
Regards,
Venkatesh R
Zoho SalesIQ
